### ISSUE TITLE
Preconditions of rstack

### ISSUE THREAD

**Issue by MikailBag** [sfackler/rstack#6]
Hello!
Could you please clarify, what conditions my application must meet so that  `rstack` will work successfully?
- As far as I undertood, child must be in paused state. Does ptrace's syscall-enter-stop suffice?
- Does tracer need root?
- Maybe, child must be spawned by tracer directly?

I ask this, because I have `Operation not permitted (os error 1)` error when using your library, and it is quite hard to debug this error, because strace doesn't work on other tracer.

**Comment by sfackler** [comment]
The traced process does not need to already be in the paused state - rstack will do that when attaching. The tracer does need permissions to ptrace the process. Search for `Ptrace access mode checking` on the ptrace man page for details on that: http://man7.org/linux/man-pages/man2/ptrace.2.html. It also needs to be able to read the `/proc` pseudo-filesystem.

Another source of permission errors is seccomp. For example, you can't use ptrace in a Docker container by default due to its sandboxing.

**Comment by MikailBag** [comment]
Regarding usual ptrace checks: they are checked on _attach_ to target process.
However in my case, child is (indirectly) spawned by tracer. Some stuff like logging syscalls and reading tracee memory works fine.

Maybe, errors happens because rstack tries to perform `ptrace(PTRACE_ATTACH)` on process, which is already traced by my tracer?

**Comment by sfackler** [comment]
Yes, you can't attach to a process that you're already attached to. We could add an option to https://docs.rs/rstack/0.3.0/rstack/struct.TraceOptions.html to say that the target is already attached and stopped.

**Comment by MikailBag** [comment]
Thanks for finding problem cause.
Do you plan implementing this feature in short future?
If don't, I will be happy to try to contribute. I hope changes required aren't big and complex.

**Comment by sfackler** [comment]
Feel free to make a PR! I don't think it should be all that complicated - you'd just need to have the flag change the behavior of the `TracedThread` object to do nothing in its constructor and `Drop` implementations: https://github.com/sfackler/rstack/blob/master/rstack/src/lib.rs#L351.
